name: "Bug Report"
description: "Submit a bug or unexpected behavior"
title: "[Bug] "
labels:
  - bug

body:
  - type: markdown
    attributes:
      value: >
        **Thank you for reporting a bug!**
        Please fill out the following details so we can help fix the issue faster.
        <br/><br/>

  - type: input
    id: summary
    attributes:
      label: "Brief Summary"
      description: "Provide a short, clear description of the bug"
      placeholder: "The application crashes with error X..."

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Include any code, commands, or actions needed to reproduce the bug"
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error

  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected Behavior"
      description: "What did you expect to happen instead?"

  - type: textarea
    id: actual-outcome
    attributes:
      label: "Actual Outcome"
      description: "What actually happened or appeared on screen?"

  - type: textarea
    id: environment
    attributes:
      label: "Environment Details (OS, version, etc.)"
      description: "e.g., Windows 10, Node 16, Docker, Browser name/version"

  - type: textarea
    id: logs-screenshots
    attributes:
      label: "Logs / Screenshots"
      description: "Paste relevant logs, stack traces, or link to screenshots"

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Anything else you’d like to add?"
