name: "Feature Request"
description: "Suggest a new idea or improvement"
title: "[Feature] "
labels:
  - enhancement

body:
  - type: markdown
    attributes:
      value: >
        **Thank you for suggesting a feature!**
        Please share as many details as you can, so we can best understand your idea.
        <br/><br/>

  - type: input
    id: feature-summary
    attributes:
      label: "Feature Summary"
      description: "Give a concise description of the new feature"
      placeholder: "Add a new user profile page..."

  - type: textarea
    id: problem-motivation
    attributes:
      label: "Problem / Motivation"
      description: "What problem does this feature solve? Who does it help?"

  - type: textarea
    id: proposed-solution
    attributes:
      label: "Proposed Solution"
      description: "How would you like to see it implemented?"

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives or Workarounds"
      description: "Are there alternative solutions or features you've considered?"

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Any designs, screenshots, or other references?"
